### ISSUE TITLE
建议多音字匹配设置为选项

### ISSUE THREAD

**Issue by CraxGrix** [xmflswood/pinyin-match#10]
我这边试着做了一下姓氏检索，输入H后检索结果会出现“许”这个姓氏。

**Comment by xmflswood** [comment]
@CraxGrix 
这里不可以简单关闭多音字的
拿 许 这个例子来说，不能保证关闭多音字后是留下了xu 还是 hu的音
---
我试了一下微信
hu 搜不出来 许
dan shan 可以搜出来 单
zeng ceng 可以搜出来 曾
猜测他是直接从字典把特别偏的音直接去掉了，例如 朱的shu 许的hu
---
我考虑的做法 2种
1.直接从原字典去除偏僻的读音 / 新建一个常见读音的字典提供使用
2.新增一个api，用户可添加一些屏蔽的读音，如 :
`PinyinMatch.addIgnore([{hu: '许'}, {shu: '朱'}])`

**Comment by SugaryPig** [comment]
> addIgnore

大佬，啥时改呀

**Comment by xmflswood** [comment]
@SugaryPig 已更新
转至https://github.com/xmflswood/pinyin-match/issues/11
