### ISSUE TITLE
建议添加 CHANGELOG.md，方便用户决定是否需要更新版本

### ISSUE THREAD

**Issue by lc-soft** [xmflswood/pinyin-match#13]
在给项目更新依赖包时，如果主版本号和次版本号有更新，会想看看更新了什么，然后再决定是否更新。

![2020-04-26 18-23-01 的屏幕截图](https://user-images.githubusercontent.com/1730073/80304811-15bd1900-87eb-11ea-9ef3-9df147dc65d9.png)

**Comment by xmflswood** [comment]
@lc-soft 
感谢建议，已经添加上了。
实际上上次更新应该更适合使用v1.0.10而不是v1.1.0
