### ISSUE TITLE
建议补充 LICENSE 文件

### ISSUE THREAD

**Issue by lc-soft** [xmflswood/pinyin-match#14]
刚看了代码库里的文件，发现没有 LICENSE 文件，建议补充 LICENSE 文件，告诉用户他们能够对你的代码做什么，不能做什么。

参考：

- https://opensource.guide/zh-hans/legal/#%E6%88%91%E7%9A%84%E9%A1%B9%E7%9B%AE%E9%80%82%E5%90%88%E4%BB%80%E4%B9%88%E6%A0%B7%E7%9A%84%E5%BC%80%E6%BA%90%E8%AE%B8%E5%8F%AF
- https://help.github.com/cn/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by xmflswood** [comment]
done
