### ISSUE TITLE
大佬问一下我咋样能用import pinyinMatch from 'pinyin-match'的方式访问这个库？

### ISSUE THREAD

**Issue by angeltxwh** [xmflswood/pinyin-match#15]
大佬是我用VUE3的，使用VITE作为编译工具

如果我用const a=  require (..)的方式在浏览器运行的时候就会提示require is not defined

如果我import pinyinMatch from 'pinyin-match' 就会说The requested module '/@modules/pinyin-match/dist/main.js' does not provide an export named 'default'

**Comment by xmflswood** [comment]
@angeltxwh 
1.1.4版本支持es module
升级后再试试

**Comment by angeltxwh** [comment]
感谢大佬的更新，我发现现在可以用下面这个引入了

`import pinyinMatch from "pinyin-match";`

但是这样虽然可以用，但是VSCODE还是会报错，说是

```
import pinyinMatch
模块 ""a:/Workspace/dsnr/web3/node_modules/pinyin-match/index"" 只能使用 "esModuleInterop" 标志进行默认导入ts(1259)
index.d.ts(6, 1): 此模块是使用 "export =" 声明的，在使用 "esModuleInterop" 标志时只能与默认导入一起使用。
```

于是我改成了

`import pinyinMatch from "pinyin-match/es/main.js";`

这样就又能运行又不报错了。。

**Comment by xmflswood** [comment]
@angeltxwh 
我自己试了下没有类似问题。
推测是vscode缓存了旧文件导致的。
你试试
1.手动删除node_modules/pinyin-match  然后再安装
2.重启vscode

**Comment by angeltxwh** [comment]
@xmflswood 
我尝试下面的操作后依然划红线提示错误

```
yarn remove pinyin-match
重启vs
yarn add pinyin-match
重启vs
```

后来发现只要我把我引入你模块的那个文件的后缀从ts改js就好了。。改回ts继续划红线

**Comment by xmflswood** [comment]
@angeltxwh 
更新到1.1.7版本
重启vs再试试？

**Comment by xmflswood** [comment]
旧版本的引入方式应该是
```
import * as Pinyin from 'pinyin-match';

console.log(Pinyin.match('你好', 'nh'));
```

我新加了tsconfig.json，现在应该可以按
```
import pinyinMatch from "pinyin-match"
```
去引入了

**Comment by angeltxwh** [comment]
貌似还是一样的，

![微信截图_20201210152527](https://user-images.githubusercontent.com/2951814/101734922-0382b780-3afc-11eb-9651-f4246ebea89b.png)

**Comment by angeltxwh** [comment]
如果按照您说的老版本的引入方式，确实是不报错的

但是执行起来有问题

```
import * as Pinyin from 'pinyin-match';

console.log(Pinyin.match('你好', 'nh'));
```

![微信截图_20201210152715](https://user-images.githubusercontent.com/2951814/101735135-61af9a80-3afc-11eb-9b7c-73d893fb3577.png)
![微信截图_20201210152735](https://user-images.githubusercontent.com/2951814/101735142-62e0c780-3afc-11eb-8241-9cd025f3da0b.png)

**Comment by xmflswood** [comment]
> 貌似还是一样的，
> 
> ![微信截图_20201210152527](https://user-images.githubusercontent.com/2951814/101734922-0382b780-3afc-11eb-9651-f4246ebea89b.png)
这里是不是报错，但是执行没问题呢？

**Comment by xmflswood** [comment]
新版本的引入 是报错，但是可以执行吗？
@angeltxwh

**Comment by angeltxwh** [comment]
@xmflswood 1.17版本可以使用下面这个来运行，但是仍然划红线

`import pinyinMatch from "pinyin-match"`

**Comment by xmflswood** [comment]
@miserylee 求助

**Comment by xmflswood** [comment]
@angeltxwh 
更新到1.18再试试？

**Comment by angeltxwh** [comment]
@xmflswood 实测已经更新到1.18版本依然有问题，解决方法删除 index.d.ts中的第六行export = Pinyin;就不会再报错了

**Comment by xmflswood** [comment]
1.1.9修复
