### ISSUE TITLE
突然的更新代码整崩了啊！

### ISSUE THREAD

**Issue by lovebigbird** [xmflswood/pinyin-match#17]
原来pinyin.match()，现在pinyin.default.match()

**Comment by xmflswood** [comment]
@lovebigbird 你是怎么引入的
环境是什么

**Comment by lovebigbird** [comment]
react项目，npm引入1.1.７版本．现在需要这样使用const pinyin = require('pinyin-match')；pinyin.default.match()

**Comment by xmflswood** [comment]
@lovebigbird 
采用import
https://github.com/webpack/webpack/issues/4742#issue-222595808

"always prefer import nowadays. Only use require if the package is not an ES Module."
