### ISSUE TITLE
增加未赋值默认值边界判断

### ISSUE THREAD

**Issue by hqzh** [xmflswood/pinyin-match#18]
有时候我传进的参数一或参数二有可能为undefined，
![image](https://user-images.githubusercontent.com/26128706/103206013-dd4f7b00-4935-11eb-9447-ab01926810fb.png)
```js
match(inputs='',keys=''){
      if(!inputs || !keys){return false}
      ........
}
```

**Comment by xmflswood** [comment]
@hqzh 1.1.8版本 加上判断了
