### ISSUE TITLE
搜索时不支持中间带空格的词

### ISSUE THREAD

**Issue by ESCxjl** [xmflswood/pinyin-match#2]
比如说：中 国 ，中间有一个空格，却匹配不到，我们项目中输入昵称时可以输入空格，这样就检索不到

试了下微信是支持的，希望能支持下这个，谢谢了。

**Comment by xmflswood** [comment]
@ESCxjl 感谢反馈，1.0.6版本已修复该错误

**Comment by ESCxjl** [comment]
> @ESCxjl 感谢反馈，1.0.6版本已修复该错误

感谢您的及时回复，我试了下，新版本已经可以通过拼音搜索带空格的词语了，但是还有一个问题就是汉字搜索还是不行，就是搜索带空格的‘中 国’时，用汉字‘中 国’（带空格）搜索不到，麻烦了。

**Comment by xmflswood** [comment]
@ESCxjl 修复了，同步更新了文档

**Comment by ESCxjl** [comment]
> @ESCxjl 修复了，同步更新了文档

感谢回复
