### ISSUE TITLE
可否暴露一个获取拼音首字母的方法

### ISSUE THREAD

**Issue by xmflswood** [xmflswood/pinyin-match#24]
可否暴露一个获取拼音首字母的方法

_Originally posted by @hqzh in https://github.com/xmflswood/pinyin-match/issues/11#issuecomment-818632505_

**Comment by xmflswood** [comment]
@hqzh
类似这样的api能满足需求吗？
pinyinMatch.getPinyin('曾') // ['zeng', 'ceng']
pinyinMatch.getPinyin('我') // ['wo']
需要首字母的话就自行去取
但是有一个难点没解决
pinyinMatch.getPinyin('曾') 可能返回的是 ['ceng', 'zeng']
即多音字pinyin顺序无法确定

具体的业务需求是什么呢？
我觉得你可能需要看看这个库能不能满足你 [pinyinJS](https://github.com/sxei/pinyinjs)
（我不倾向与在pinyinMatch里面做类似的事情）

**Comment by xmflswood** [comment]
我个人想到需要的场景：
联系人列表，右边需要显示拼音首字母，可以帮助快速定位。
但是这里就需要对多音字做顺序的处理
比如
曾 应该优先拿 zeng 的音，而不是 ceng
单 应该优先拿 shan 的音，而不是 dan

**Comment by hqzh** [comment]
@xmflswood 嗯。我看了一下源码，当有多音字确实无法处理，我用了这个https://github.com/hotoo/pinyin库处理
