### ISSUE TITLE
能否对识别的结果进行排序？

### ISSUE THREAD

**Issue by Michael18811380328** [xmflswood/pinyin-match#30]
<img width="464" alt="截屏2021-12-20 18 33 18" src="https://user-images.githubusercontent.com/37589122/146753694-74c7c5ad-c828-4b4f-a9b5-110d66c0a40a.png">
在网页端使用时，如果输入拼音，现在搜索的结果是原始的数组顺序，能否支持加一个参数，可以按照匹配的汉字顺序进行输出？这样便于用户找到需要的选项？另外，看到核心代码中有一点点性能可以提升，已经提交 PR，麻烦大佬看一下

**Comment by Michael18811380328** [comment]
例如，用户想要的结果：
1、哈
2、海
3、汉

**Comment by xmflswood** [comment]
感谢提pr
关于排序我个人认为用户的期望是不统一的。
a. 如微信通讯人列表，这里的排序应当是以最近聊天时间顺序决定（即原始的数组顺序）
b. 其他情况 大多数应该是 以键入的pinyin在文本中寻找到位置顺序决定（这里是考虑用户大多数习惯还是从第一个汉字的pinyin开始键入搜索）
比如输入 ha
我认为 列表中第一个字符为 ha 开头的应该放在前面
顺序应当是：
1.**哈**文
2.**汉**庭
3.**寒**冷
4.元江**哈**尼族
c.即你提到的顺序

@Michael18811380328

**Comment by xmflswood** [comment]
对b进行各补充说明
有酒店列表：
齐齐哈尔大酒店
汉庭酒店
维也纳大酒店

输入“ha”
应当是汉庭酒店排在第一位

**Comment by Michael18811380328** [comment]
确实，不同产品搜索结果顺序不一样（微信或者其他产品）
