### ISSUE TITLE
为什么要把 rollup 作为 Dependencies 依赖呢？

### ISSUE THREAD

**Issue by sarlery** [xmflswood/pinyin-match#33]
看 npm 上最新的版本，Dependencies 中有 rollup，在项目中使用这个包时会额外的下载 rollup，是否应该把 rollup 作为开发依赖？

**Comment by xmflswood** [comment]
不清楚为什么被放到Dependencies中，package.json 我是写到 dev中的

**Comment by LvGuoQing** [comment]
![image](https://user-images.githubusercontent.com/17480732/184793443-74fdd8f0-ca00-46db-b712-d49e8aeb6512.png)
npm中发布的包中rollup是作为Dependencies，install之后，package.json中也是Dependencies，github中的代码中是dev，是不是需要重新发布一个新的版本

**Comment by xmflswood** [comment]
重新发版本后 站点上已经没显示了（我没改相关代码配置）
