### ISSUE TITLE
u, v匹配,一个很常见的错误

### ISSUE THREAD

**Issue by liuyike98** [xmflswood/pinyin-match#37]
lueduo lveduo 都是"掠夺", 但是只能匹配出 lveduo ,其实很多人打字的时候打的是u而不是v

**Comment by xmflswood** [comment]
谢谢反馈，下个小版本修正。（预计本周）
此外还有 虐 存在问题。

**Comment by liuyike98** [comment]
> 谢谢反馈，下个小版本修正。（预计本周） 此外还有 虐 存在问题。

好像不仅仅是nue(虐),我现在每次都要搜两边, 第二遍是把字符串里所有的u替换成v再搜一遍...

**Comment by xmflswood** [comment]
我看简体库里的 ve 读音
发现只有  lve nve ，我打算把这俩也加到 lue nue 里面
@liuyike98

**Comment by liuyike98** [comment]
是这样的, vn=>变成整体认读就是yun,事实上是yvn,但写作yun, 这就造成了一些人打字方法不同,我前几天发现朋友一直在打yvn,而我一直是用的yun, 而用pinyinMatch:
`PinyinMatch.match("1.云服务","yvn")`返回的是false, 但是事实上用微软拼音输入法是可以打出来,原因就是我开头说的那种情况

**Comment by xmflswood** [comment]
@liuyike98 
查询了资料，结论如下：
1. ü 遇到 j、q、x 写拼音的时候去掉两点 写作 u，有："ju""jun""jue""juan""qu""qun""que""xuan""xu""xue"
2. üe（越） ün （云）ü（鱼）üan(元) 这几个读音，去掉两点，前面补上y，有："yu""yuan""yue""yun"
3. 虐(nüe) 略(lüe) 女(nü) 绿(lü)，正确写法不应省略两点，所以都打成 v 才是正确的，只是并没有 nue、lue的读音，所以很多输入法以及输入习惯都会直接用 nue、lue代替

综上，计划对字库做如下补充处理：
1.  "ju""jun""jue""juan""qu""qun""que""xuan""xu""xue""yu""yuan""yue""yun" 增加 "jv""jvn"....的读音处理
2. nve、lve 增加 "nue" "lue"的读音处理

**Comment by liuyike98** [comment]
@xmflswood 是的,这几个确实都是👍

**Comment by xmflswood** [comment]
@liuyike98 
1.2.4 已做上述优化处理
