### ISSUE TITLE
Feat： how to replace repeat words ? ('aba', 'a')=>[1,2]

### ISSUE THREAD

**Issue by zhuzilv** [xmflswood/pinyin-match#41]
('aba', 'a')=>[1,2] : now;

demand ：
 ('aba', 'a')=>[[0,1],[1,2]]

**Comment by xmflswood** [comment]
@zhuzilv 
I have tested the example, and it worked fine.
![impicture_20231011_203930](https://github.com/xmflswood/pinyin-match/assets/13427833/e7b6b735-9cdc-408c-8560-3c1603f38593)

In response to the demand for multiple matches , I have no plans to implement it currently.
Maybe [pinyin-pro](https://github.com/zh-lx/pinyin-pro) can help you.
