### ISSUE TITLE
可以做前缀子串匹配吗？

### ISSUE THREAD

**Issue by pansong291** [xmflswood/pinyin-match#44]
比如 `重庆` 的拼音是
```
chong qing
zhong qing
```
其中 `重` 的前缀子串有：
```
c
ch
cho
chon
chong
z
zh
zho
zhon
zhong
```
`庆` 的前缀子串有：
```
q
qi
qin
qing
```
那么按照前缀匹配的话，以下输入组合都可以进行匹配：
```
cq
cqi
cqin
cqing
chq
chqi
chqin
chqing
choq
choqi
choqin
choqing
chonq
chonqi
chonqin
chonqing
chongq
chongqi
chongqin
chongqing
zq
zqi
zqin
zqing
zhq
zhqi
zhqin
zhqing
zhoq
zhoqi
zhoqin
zhoqing
zhonq
zhonqi
zhonqin
zhonqing
zhongq
zhongqi
zhongqin
zhongqing
```

**Comment by xmflswood** [comment]
目前不考虑，设计规则以微信app为准。具体可见：https://juejin.cn/post/6844904161461403661
做前缀子串匹配，主要要避免元音问题。例如
最爱 zui ai
按上述规则，输入 zai 也会比配到最爱，但绝大多数时候，用户实际要的是 `z a i`三个字，或者 `zai` 这一个字。

**Comment by pansong291** [comment]
没错，我的想法就是 `zai` 既要能匹配到 `在` 也要能匹配到 `最爱`。个人认为排除掉 `最爱` 反而不太方便。毕竟一般的拼音输入法也是支持 `zai` 检索出 `最爱` 的。
