### ISSUE TITLE
常用字搜索不到

### ISSUE THREAD

**Issue by LZJ30** [xmflswood/pinyin-match#47]
您好！该插件存在常用字搜索不到的情况，查看源码发现没有收录“啰”字，但是常用搜索“哈啰单车”，能否将“啰”字加入常用简体汉字中，谢谢！

**Comment by xmflswood** [comment]
预计本周末调整发布
@LZJ30

**Comment by xmflswood** [comment]
@LZJ30 1.2.6 已增加

**Comment by LZJ30** [comment]
> @LZJ30 1.2.6 已增加

好的，谢谢。
