### ISSUE TITLE
PinyinMatch.match("淘宝", "bao") 等于false

### ISSUE THREAD

**Issue by tongjieme** [xmflswood/pinyin-match#6]
<img width="266" alt="Screen Shot 2019-04-05 at 11 48 57 PM" src="https://user-images.githubusercontent.com/1511418/55640062-6e470000-57fd-11e9-8e70-5f88393539eb.png">

**Comment by xmflswood** [comment]
@tongjieme 原拼音库里没有bao这个音，1.0.8版本已加上。
