### ISSUE TITLE
PinyinMatch.match("卡号打开", "ka") 

### ISSUE THREAD

**Issue by freekami** [xmflswood/pinyin-match#7]
搜索结果匹配到“开”字而不是“卡”
看起来似乎是字库排序的问题?
谢谢

**Comment by xmflswood** [comment]
![image](https://user-images.githubusercontent.com/13427833/77493912-57bb0e00-6e7f-11ea-87e5-74bb85ea2f17.png)
![image](https://user-images.githubusercontent.com/13427833/77494073-baaca500-6e7f-11ea-9fd6-78623de291b8.png)
@freekami 我做了下测试 看起来没有问题

**Comment by xmflswood** [comment]
@freekami 
感谢反馈
源码中 getIndex 方法存在问题
我周末修复一下

**Comment by xmflswood** [comment]
@freekami v1.1.0版本已修正该问题

**Comment by xmflswood** [comment]
@freekami 
v1.1.0版本已修正该问题
![image](https://user-images.githubusercontent.com/13427833/77920050-89453680-72d0-11ea-907d-10a68321d1c5.png)

**Comment by freekami** [comment]
感谢!
